### ISSUE TITLE
SoW (or planning) related to Tracey/QuTiCon - two customers

### ISSUE THREAD

**Issue by buep** [Praqma/josra#31]
This is more tricky because they are related, and to some extend part of the skattefunn project.

Somehow it need to be a SoW or project defined around this.

I'll let you @lakruzz and @meekrosoft do something about this. @RandomSort you're also involved.

**Comment by buep** [comment]
@RandomSort and @MadsNielsen  can you make sure your notes are available, either on this issue or link to somewhere for Lars, Mike and Andrey.

Mike and Lars will coordinate this project, because it needs to be taking into account the generic and customer specific parts due to funding.

But I think you could maybe make a write-up mean while, so we at least have a conclusion on the meeting, what our members want and so forth.

Though it is not going to be statement of work, we will go out to get funding for, it could be explained almost like one so we have.

Would it make sense?

**Comment by buep** [comment]
@RandomSort @MadsNielsen what is status now here 2 days after?

**Comment by buep** [comment]
I sent @MadsNielsen and @RandomSort  a personal mail now...

**Comment by RandomSort** [comment]
Sorry for the lack of communication.
The current status is that @MadsNielsen will do a two-day workshop on-site with Flemming.
We should be able to move Tracey from the PoC state that it is in at the moment to an actually running MVP.
Focus will be on ease of generating, and adding new events. 
And the simplest possible visualization in Neo4J.

The hope is that this will be enough to convince others to join forces.

Lars has called a meeting with me and Mike in order to coordinate efforts and plan next steps.

**Comment by buep** [comment]
@MadsNielsen promised to give a status in josra slack and close this issue with a link to it

**Comment by MadsNielsen** [comment]
Wrote wrapup in a post: https://josra.slack.com/files/mads-nielsen/F5GS2645S/Tracey_QuTiCon_Status
